### ISSUE TITLE
Unable to compile on MacOs

### ISSUE THREAD

**Issue by wviana** [oitofelix/mininim#14]
When trying to compile branch `next` 

on `./configure LUA_LIB="-llua50 -llualib50"` I got:

``` 
checking for a Lua interpreter with version >= 5.0, < 5.1... none
configure: error: MININIM requires Lua 5.0 (or superior)
```

on `lua -v` :

``` 
Lua 5.3.4  Copyright © 1994-2017 Lua.org, PUC-Rio
```

**Comment by oitofelix** [comment]
```
configure: error: MININIM requires Lua 5.0 (or superior)
```

This message is misleading.  It must read that MININIM requires Lua 5.0 or superior as long as it's not greater than 5.1. (The message above it makes that clear, though.)

Therefore, in order to build MININIM, you need a Lua installation meeting those requirements.  I'd suggest the latest version within those constraints: [Lua 5.0.3](https://www.lua.org/ftp/lua-5.0.3.tar.gz).
